name: telecom
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_it: ^7.2.0
  path_provider: ^2.0.14
  path: ^1.8.3
  sqflite: ^2.2.7
  flutter_svg: ^2.0.7
  dartz: ^0.10.1
  equatable: ^2.0.5
  geocoding: ^2.1.0
  url_launcher: ^6.1.11
  intl: ^0.18.1
  table_calendar: ^3.0.9
  geolocator: ^9.0.2
  shared_preferences: ^2.1.2
  fl_chart: ^0.62.0
  pdf: ^3.10.1
  image_picker: ^0.8.9
  flutter_bloc: ^8.1.3
  open_file: ^3.3.2
  lottie: ^2.4.0
  keyboard_dismisser: ^3.0.0
  flutter_dotenv: ^5.1.0
  
  syncfusion_flutter_xlsio: ^22.2.8
  flutter_native_splash: ^2.3.9

  linearprogress: 
    path: linearprogress/

dev_dependencies:
  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true 
  image_path: "assets/pylone.png"
  min_sdk_android: 21  
  web:
    generate: true
    image_path: "assets/pylone.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/pylone.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/pylone.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/pylone.png"
  color_dark: "#121212"
  image_dark: "assets/pylone.png"
   

  android_12:
    image: "assets/pylone.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/pylone.png"
    icon_background_color_dark: "#121212"

  web: false


flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/svg/
    - assets/project/
    - assets/spinner.gif
    - assets/pylone.png
    - .env

