name: telecom
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_it: ^7.2.0
  path_provider: ^2.0.14
  path: ^1.8.3
  sqflite: ^2.2.7
  flutter_svg: ^2.0.7
  dartz: ^0.10.1
  equatable: ^2.0.5
  geocoding: ^3.0.0
  url_launcher: ^6.2.5
  intl: ^0.19.0
  table_calendar: ^3.1.1
  geolocator: ^11.0.0
  shared_preferences: ^2.1.2
  fl_chart: ^0.67.0
  pdf: ^3.10.1
  image_picker: ^1.0.7
  flutter_bloc: ^8.1.4
  open_file: ^3.3.2
  lottie: ^3.1.0
  keyboard_dismisser: ^3.0.0
  flutter_dotenv: ^5.1.0
  rxdart: ^0.27.7
  syncfusion_flutter_xlsio: ^25.1.37
  flutter_native_splash: ^2.4.0

  linearprogress: 
    path: linearprogress/

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_launcher_icons: "^0.13.1"
  mocktail: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter 
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true 
  image_path: "assets/pylone.png"
  min_sdk_android: 21  
  web:
    generate: true
    image_path: "assets/pylone.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/pylone.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/pylone.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/pylone.png"
  color_dark: "#ffffff"
  image_dark: "assets/pylone.png"
  android_gravity: center
  android_12:
    image: "assets/pylone.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/pylone.png"
    icon_background_color_dark: "#ffffff"

  web: false


flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/svg/
    - assets/project/
    - assets/spinner.gif
    - assets/pylone.png
    - assets/route.png
    - .env

